### ISSUE TITLE
Question about scaling in and around get_state()

### ISSUE THREAD

**Issue by ihopethiswillfi** [AI4Finance-Foundation/FinRL-Metaverse#12]
Hi, I see various scaling operations going on in some of the environments, e.g. in env_multiple_crypto.py there are lines like this:
```
state =  np.hstack((self.cash * 2 ** -18, self.stocks * 2 ** -3))
normalized_tech_i = tech_i * 2 ** -15
reward = (next_total_asset - self.total_asset) * 2 ** -16
```
I am wondering how these numbers were determined.  Am I right in that these should be dependendent on the input data and needs to be made dynamic instead of hardcoded?

**Comment by rayrui312** [comment]
1. We use these numbers to make the features roughly around 1.
2. Yes, you're right. It should be dynamic. These hardcoded numbers only work roughly. 

We will update it and use a dynamic one.
